export {Loader} from './Loader'
export {Navbar} from './Navbar'
export {Footer} from './Footer'
export {Welcome} from './Welcome'
export {Services} from './Services'
export {Transactions} from './Transactions'